package com.example.inchesconverter

import android.annotation.SuppressLint
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class MainActivity : AppCompatActivity() {
//    initialize variables
    private lateinit var editTextInches: EditText
    private lateinit var convertButton: Button
    private lateinit var textViewCentimeter: TextView

//    constant variable
    private val inchValue: Double = 2.54

//    generated by the system
    @SuppressLint("SetTextI18n")


    override fun onCreate(savedInstanceState: Bundle?) {
//        generated by system
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_main)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }

//        start here
        editTextInches = findViewById(R.id.editTextInches)
        convertButton = findViewById(R.id.button_covert)
        textViewCentimeter = findViewById(R.id.textViewConvert)

//        if button clicked
        convertButton.setOnClickListener {
            if(editTextInches.text.toString().isNotEmpty()) {
                val centimeterResult = editTextInches.text.toString().toDouble() * inchValue

//                assign the result
                textViewCentimeter.text = "$centimeterResult cm"
            } else {
                textViewCentimeter.text = getString(R.string.textView_text_warning)
            }
        }

    }
}